---
services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_SERVER_DOMAIN: grafana
      GF_SERVER_ROOT_URL: https://grafana/
      GF_SECURITY_ADMIN_EMAIL: admin@home.joe.nyland.io
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: smtp.home.joe.nyland.io:25
      GF_SMTP_SKIP_VERIFY: true
      GF_SMTP_FROM_ADDRESS: grafana@home.joe.nyland.io
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.rule: Host(`grafana`)
      traefik.http.routers.grafana.middlewares: trusted-ipallowlist
    volumes:
      - /containers/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=3y" # Defaults to 15 days
    volumes:
      - /containers/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /containers/prometheus/data:/prometheus
    labels:
      traefik.enable: true
      traefik.http.routers.prometheus.rule: Host(`prometheus`)
      traefik.http.routers.prometheus.middlewares: trusted-ipallowlist

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    restart: unless-stopped
    ports:
      - 8181:8181
    command:
      - "--port=8181" # Default is 8080
      - "--docker_only=true"
      - "--housekeeping_interval=5s" # How often stats are collected
      - "--store_container_labels=false"
      - "--disable_root_cgroup_stats=true"
      - "--disable_metrics=disk,hugetlb,sched"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/zfs:/dev/zfs
    environment:
      CADVISOR_HEALTHCHECK_URL: http://localhost:8181/healthz # Default is http://localhost:8080/healthz

  graphql-exporter:
    image: ricardbejarano/graphql_exporter
    restart: unless-stopped
    ports:
      - 9199:9199

  plex-exporter:
    image: ghcr.io/jsclayton/prometheus-plex-exporter
    restart: unless-stopped
    ports:
      - 32490:9000
    environment:
      PLEX_SERVER: ${PLEX_SERVER:-http://plex:32400}
      PLEX_TOKEN: ${PLEX_TOKEN:?PLEX_TOKEN is required}

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    restart: unless-stopped
    command: sonarr
    ports:
      - 9707:9707
    environment:
      PORT: 9707
      URL: http://sonarr:8989
      API_KEY: ${SONARR_API_KEY:?SONARR_API_KEY is required}
      ENABLE_ADDITIONAL_METRICS: true # Allows reporting of additional metrics, including quality

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    restart: unless-stopped
    command: radarr
    ports:
      - 9708:9708
    environment:
      PORT: 9708
      URL: http://radarr:7878
      API_KEY: ${RADARR_API_KEY:?RADARR_API_KEY is required}

  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    restart: unless-stopped
    command: lidarr
    ports:
      - 9709:9709
    environment:
      PORT: 9709
      URL: http://lidarr:8686
      API_KEY: ${LIDARR_API_KEY:?LIDARR_API_KEY is required}
      ENABLE_ADDITIONAL_METRICS: true # Allows reporting of additional metrics, including quality

  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    restart: unless-stopped
    command: prowlarr
    ports:
      - 9710:9710
    environment:
      PORT: 9710
      URL: http://prowlarr:9696
      API_KEY: ${PROWLARR_API_KEY:?PROWLARR_API_KEY is required}

  sabnzbd-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    restart: unless-stopped
    command: sabnzbd
    ports:
      - 9711:9711
    environment:
      PORT: 9711
      URL: http://sabnzbd:8090
      API_KEY: ${SABNZBD_API_KEY:?SABNZBD_API_KEY is required}

  whisparr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    restart: unless-stopped
    command: sonarr
    ports:
      - 9769:9769
    environment:
      PORT: 9769
      URL: http://whisparr:6969
      API_KEY: ${WHISPARR_API_KEY:?WHISPARR_API_KEY is required}
      ENABLE_ADDITIONAL_METRICS: true # Allows reporting of additional metrics, including quality

networks:
  default:
    enable_ipv6: true
